### ISSUE TITLE
Icon missing on connect widget for dektrium/yii2-user

### ISSUE THREAD

**Issue by thecortex** [kotchuprik/yii2-instagram-authclient#1]
Hey,

The icon is missing in the sprite authchoice.png used to render the connect widget in dektrium/yii2-user

Is there a work-around or are you going to integrate with dektrium?

Thanks~

**Comment by kotchuprik** [comment]
hey, It's not dektium extension. It's extension for yii2-auth and I'm not sure that I need or should integrate the extension with dektrium

**Comment by thecortex** [comment]
Okay, thanks for clarification.

**Comment by kotchuprik** [comment]
thank you for the issue, have a nice day :)
