### ISSUE TITLE
{"error_type": "OAuthException", "code": 400, "error_message": "Invalid scope: []"}

### ISSUE THREAD

**Issue by Ildar5** [kotchuprik/yii2-instagram-authclient#10]
появляется вот такая ошибка при попытке логина через instagram.
{"error_type": "OAuthException", "code": 400, "error_message": "Invalid scope: []"}
все настраивал по инструкции.
                'instagram' => [
                    'class' => 'kotchuprik\authclient\Instagram',
                    'clientId' => env('INSTAGRAM_CLIENT_ID'),
                    'clientSecret' => env('INSTAGRAM_CLIENT_SECRET'),
                ],
помогите разобраться.

**Comment by chuprik** [comment]
Судя по всему инстаграм что-то на своей стороне поменял, попробую посмотреть сегодня и отпишусь.

**Comment by chuprik** [comment]
Проверил, у меня всё ок. Есть возможность CLIENT_ID и CLIENT_SECRET скинуть? возможно с новыми ключами эта проблема есть

**Comment by Ildar5** [comment]
> Проверил, у меня всё ок. Есть возможность CLIENT_ID и CLIENT_SECRET скинуть? возможно с новыми ключами эта проблема есть

К сожалению пока нет, попробую тестовую версию создать.
