### ISSUE TITLE
Setting unknown property: kotchuprik\authclient\Instagram::consumerKey

### ISSUE THREAD

**Issue by Caravus** [kotchuprik/yii2-instagram-authclient#2]
Error in docs:
>Setting unknown property: kotchuprik\authclient\Instagram::consumerKey

Fix:
>   'instagram' => [
>                    'class' => 'kotchuprik\authclient\Instagram',
>                    'clientId' => '...',
>                    'clientSecret' => '...',
>                ],

**Comment by kotchuprik** [comment]
thanks, could you to do pull request with fix? I would like to mark you in the history of project :)
