### ISSUE TITLE
icon missing oauth in widget

### ISSUE THREAD

**Issue by olissongs** [kotchuprik/yii2-instagram-authclient#6]
Hi,
how can i make an icon shown on the
yii\authclient\widgets\AuthChoice::widget

there is no icon shown, but a link is set. white on white.

how can i fix it?

**Comment by chuprik** [comment]
hey, could you me your code in view?

**Comment by olissongs** [comment]
hey, sure
`<?= yii\authclient\widgets\AuthChoice::widget([
            'baseAuthUrl' => ['site/auth'],
            'popupMode' => false,
        ]) ?>`

**Comment by olissongs** [comment]
here the html sourc-code
`<li><a class="instagram auth-link" href="/site/auth?authclient=instagram" title="Instagram"><span class="auth-icon instagram"></span></a></li>`

Facebook
`<a class="facebook auth-link" href="/site/auth?authclient=facebook" title="Facebook"><span class="auth-icon facebook"></span></a>
`
so i don't know where the auth-icon-classes are defiened

**Comment by olissongs** [comment]
vendor/yiisoft/yii2-authclient/src/assets/authchoice.png

no instagram in there

**Comment by nismangulov** [comment]
@olissongs 

If you want to use AuthChoice with third-party auth clients, you need to define icons on your own by adding css like this:

```
.auth-icon.instagram {
    background: url(instagram.png) no-repeat;
}
```

You can add it to existing css file or use `registerCss` function in view.
