### ISSUE TITLE
getting error 404 coming back from instagram

### ISSUE THREAD

**Issue by olissongs** [kotchuprik/yii2-instagram-authclient#8]
Hi,
love this plugin, by using.

one error i get when login with instagram, started good going to instagram oauth page, logied in, coming back to site/auth getting error 404

`site/auth?code=e...a&state=e...8`

then error page 404 comes up

`public function onAuthSuccess($client)
    {
        yii::info("onsuccess in");
        (new AuthHandler($client))->handle();
        yii::info("onsuccess out");
    }`

in actions
`'auth' => [
                'class' => 'yii\authclient\AuthAction',
                'successCallback' => [$this, 'onAuthSuccess'],
            ],`

with facebook its working fine, but the instagram thing makes some trouble i don't know why?
by the way, all url are registered in instagram.

**Comment by chuprik** [comment]
try to add logs and find where is failing

**Comment by olissongs** [comment]
ok,

starting in site/login with widget 
`<?= yii\authclient\widgets\AuthChoice::widget([
                'baseAuthUrl' => ['site/auth'],
                'popupMode' => false,
            ]) ?>`

the instagram button is linked to:
`.../site/auth?authclient=instagram`

goes to

`https://www.instagram.com/accounts/login/?next=/oauth/authorize%3Fclient_id%3D3....26%26response_type%3Dcode%26redirect_uri%3Dhttps%3A/..../site/auth%3Fauthclient%3Dinstagram%26xoauth_displayname%3DMyApp%26state%3Dc8ad1...5889b0`

Logging in in Instagram redirect to:

`https://.../site/auth?code=05a....&state=c8ad1....89b0`

here comes the 404 error, because of getting no clientid in 

yii\web\NotFoundHttpException in /.../vendor/yiisoft/yii2-authclient/src/AuthAction.php:197 Stack trace: #0 [internal function]: yii\authclient\AuthAction->run()


if i repeat this again:

site/login
press instagram button
then i am  suddenly logged in 

???

**Comment by chuprik** [comment]
> yii\web\NotFoundHttpException in /.../vendor/yiisoft/yii2-authclient/src/AuthAction.php:197 Stack trace: #0 [internal function]: yii\authclient\AuthAction->run()

:)

be bravely with debugging ;)

**Comment by olissongs** [comment]
??
why do i get not authclient=instagram in the return url from instagram? in the App Registration i did registrate this with authclient

**Comment by olissongs** [comment]
wrong button pressed its still opened :-)

**Comment by chuprik** [comment]
have no idea, please, debug your code

**Comment by olissongs** [comment]
can i set the redirect url manually?

i don't know where to catch the return

**Comment by chuprik** [comment]
https://github.com/yiisoft/yii2-authclient/blob/master/docs/guide/quick-start.md

URL creates by yiii2-authclient not my extension

**Comment by olissongs** [comment]
i have no idea how to find this behavior, done debug inf, browser developer tools ,,,
but it seems that instagram is cutting it out, can this be, then a lot more people must have this problem.

thats the browser infos
i registered in instagram my app redirurl like that

`myappurl/site/auth?authclient=instagram`

so the redirecturl i expected should be like that:

`myappurl/site/auth?authclient=instagram&code=....`

but it comes:

`myappurl/site/auth?code=...`

using developer tools in browser i recognize:

`https://www.instagram.com/accounts/login/ajax/`

`username=myusernam
password=mypassword
queryParams={"next":"/oauth/authorize?client_id=theclientid&   
response_type=code&redirect_uri=myappurl/site/auth?authclient=instagram&
xoauth_displayname=MyApps&state=statenumbers"}`

so here is it ok the next get request is wrong

`https://www.instagram.com/oauth/authorize?client_id=theclientid&
response_type=code&redirect_uri=myappurl%2Fsite%2Fauth%3Fauthclient&
xoauth_displayname=MyApps&state=statenumbers`

`client_id=theclientid
response_type=code
redirect_uri=myappurls%2Fsite%2Fauth%3Fauthclient
xoauth_displayname=MyApp
state=statenumbers`

here is the =instagram gone

the redirected url from instagram is then:

`myappurl/site/auth?code=codenumbers&state=statenumbers`

so this ist wrong the authclient=instagram is gone lost, i dont know why

**Comment by olissongs** [comment]
i found a workaround but i don't think thats the best solution

     class AuthAction extends \yii\authclient\AuthAction
     {

    public function run()
    {
     $clientId = Yii::$app->getRequest()->getQueryParam($this->clientIdGetParamName);
     if (!empty($clientId)) {
        $collection = Yii::$app->get($this->clientCollection);
        if (!$collection->hasClient($clientId)) {
            throw new NotFoundHttpException("Unknown auth client '{$clientId}'");
        }
        $client = $collection->getClient($clientId);

        return $this->auth($client);
    } else {
        $clientId = 'instagram';
        $collection = Yii::$app->get($this->clientCollection);
        if (!$collection->hasClient($clientId)) {
            throw new NotFoundHttpException("Unknown auth client '{$clientId}'");
        }
        $client = $collection->getClient($clientId);
 
        return Yii::$app->response->redirect(['/site/auth','authclient'=>'instagram']);

    }

     // throw new NotFoundHttpException();
      }
      }

**Comment by chuprik** [comment]
the problem is not in my component
