### ISSUE TITLE
Getting Error when in an other Browser Tab as other InstagramUser

### ISSUE THREAD

**Issue by olissongs** [kotchuprik/yii2-instagram-authclient#9]
When logged in in Instagram or other App using Instagram Login, i get an error

`{"error_type": "OAuthForbiddenException", "code": 403, "error_message": "You are not a sandbox user of this client"}`

may this  actually clear that this user is not in my sandbox acoount, but i think i will get an similar error

can i catch this situation before logging in or is there a solution where i can switch the login?

where is the information set? Cookie instagram?

**Comment by chuprik** [comment]
https://stackoverflow.com/search?q=You+are+not+a+sandbox+user+of+this+client
